//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.GUI.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int employeeID { get; set; }
        public string userName { get; set; }
        public string fullName { get; set; }
        public System.DateTime dob { get; set; }
        public int gender { get; set; }
        public string placeOfBirth { get; set; }
        public string ssn { get; set; }
        public System.DateTime issuedDate { get; set; }
        public string issuedPlace { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public string currentLocation { get; set; }
        public string linkImagine { get; set; }
        public int posID { get; set; }
        public int depID { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblPosition tblPosition { get; set; }
    }
}
